baseURL = 'https://kmrd.dev'
languageCode = 'en-us'
title = 'kmrd.dev'
theme = "uBlogger"
enableGitInfo = true
enableEmoji = true

[permalinks]
  posts = "/:year/:title/"

[params]
  # uBlogger theme version
  version = "2.0.X"

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "static/images/me.jpeg"
      title = ""
      subtitle = "Hey there, I am a Network Engineer with a passion for Automation and Product Development."
      social = true

  [params.social]
    GitHub = "karimra"
    Twitter = "karimtw_"
    Linkedin = "karim-radhouani"

[menu]
#   [[menu.main]]
#     identifier = "projects"
#     pre = ""
#     post = ""
#     name = "Projects"
#     url = "/projects/"
#     title = ""
#     weight = 1
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false